### ISSUE TITLE
Searchrefiner demo gives give HTTP 502 Bad Gateway

### ISSUE THREAD

**Issue by bevankoopman** [ielab/searchrefiner#72]
The main demo at [https://ielab-sysrev2.uqcloud.net](https://ielab-sysrev2.uqcloud.net) gives a 502.

**Comment by hscells** [comment]
Hmm. Since the Bond group maintains an "in production" version of searchrefiner, we should try to make this URL redirect to it: https://sr-accelerator.com/#/searchrefinery

I'm not sure how feasible this is for me to do any more, but at the very least I will change the existing links that point to a demo to this Bond URL.

Thanks for letting me know!

**Comment by hscells** [comment]
We now have a dedicated EC2 instance to run searchrefiner 😊
